### ISSUE TITLE
Cambio de estilo en el boton de "leer reseña completa"

### ISSUE THREAD

**Issue by biancapallaro** [lanacioncom/books16#28]
![image](https://cloud.githubusercontent.com/assets/17811940/23922758/5bcca14e-08e2-11e7-97df-01d8fc1a69e4.png)

**Comment by cbertelegni** [comment]
@ploscri Este no se si cambiarlo ya que puede haber mas de un link y ese botón no va a quedar bueno... me parece que como está queda bien o le haría algo un poco mas simple... que opinas?

![image](https://cloud.githubusercontent.com/assets/1827151/25442795/5f06e480-2a7c-11e7-8043-da7bea8d0510.png)
