### ISSUE TITLE
Ajustes en el layout

### ISSUE THREAD

**Issue by ploscri** [lanacioncom/books16#31]
![image](https://cloud.githubusercontent.com/assets/4295416/24985236/54480c76-1fc9-11e7-8f8f-955a426ead35.png)

**Comment by ploscri** [comment]
**Logo ideas**

![ideas](https://cloud.githubusercontent.com/assets/4295416/24985628/cd99b7b2-1fcb-11e7-91f5-bcf0b738f300.png)

**Comment by ploscri** [comment]
**Dibujo provisorio**

![dibujo](https://cloud.githubusercontent.com/assets/4295416/24985725/71a5fa5a-1fcc-11e7-81b5-c2ac0a2d0dc0.jpg)

**Comment by cbertelegni** [comment]
@ploscri 
* Cómo se va a ver esto en responsive? 
* Qué tamaño va a tener?
* Siempre va a ocupar ese espacio al costado del título?
