### ISSUE TITLE
SACAR BULLET POINT AL LADO DE "LEER RESEÑA COMPLETA". 

### ISSUE THREAD

**Issue by biancapallaro** [lanacioncom/books16#50]
![image](https://cloud.githubusercontent.com/assets/17811940/25641189/2ccf5fe6-2f69-11e7-9b1c-dc909a80859b.png)

**Comment by cbertelegni** [comment]
que pasa cuando hay mas de un link? si pensamos poner mas de un link me parece que esta bien que tenga el bullet ya que en realidad es un listado de links.

@biancapallaro ¿?
